package com.semperti.hipotecario.poc.fuse.cobis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-02-03T12:43:48.543-03:00
 * Generated source version: 3.0.12
 * 
 */
@WebServiceClient(name = "cobisService", 
                  wsdlLocation = "file:/tmp/cobis.wsdl",
                  targetNamespace = "http://cobis.poc.hipotecario.semperti.com/") 
public class CobisService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cobis.poc.hipotecario.semperti.com/", "cobisService");
    public final static QName CobisServicePort = new QName("http://cobis.poc.hipotecario.semperti.com/", "CobisServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/tmp/cobis.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CobisService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/tmp/cobis.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CobisService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CobisService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CobisService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CobisService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CobisService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CobisService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CobisService
     */
    @WebEndpoint(name = "CobisServicePort")
    public CobisService getCobisServicePort() {
        return super.getPort(CobisServicePort, CobisService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CobisService
     */
    @WebEndpoint(name = "CobisServicePort")
    public CobisService getCobisServicePort(WebServiceFeature... features) {
        return super.getPort(CobisServicePort, CobisService.class, features);
    }

}
